### ISSUE TITLE
How to create a bot using tourmaline that reads any messages from the chat and responds to them?

### ISSUE THREAD

**Issue by VanyaNeytrino** [protoncr/tourmaline#33]
Actually the question I asked. I can't figure out how to create such a bot

**Comment by watzon** [comment]
Pretty simple. If you want to make a method that responds to any incoming message you just need to use the `On` annotation. For example:

```crystal
@[On(:message)]
def on_message(update)
  if message = update.message
    # do stuff here
  end
end
```

For now the method decorated with the `On` annotation always has to accept an `Update` object, which has an optional `message` property. So to make crystal happy you'd either have to do `message = update.message.not_nil!` (since we know that in this case the message will not be nil) or do a simple guard clause like I did in the example above.

**Comment by VanyaNeytrino** [comment]
thank you for your answer
